# ===================================================================
# ABARROTE CLOUD - DESARROLLO LOCAL
# ===================================================================

spring.application.name=abarrote-cloud

# ===================================================================
# POSTGRESQL
# ===================================================================

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/abarrote_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# FLYWAY
# ===================================================================

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.default-schema=public
spring.flyway.table=flyway_schema_history

# Permite incorporar Flyway a la base local existente.
spring.flyway.baseline-on-migrate=false
spring.flyway.baseline-version=1
spring.flyway.baseline-description=Esquema existente antes de Flyway

spring.flyway.validate-on-migrate=true
spring.flyway.clean-disabled=true

# ===================================================================
# JPA / HIBERNATE
# ===================================================================

# Hibernate ya no modifica tablas.
# Flyway controla la estructura.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL se detecta automáticamente.
spring.jpa.open-in-view=false

# ===================================================================
# SERVIDOR
# ===================================================================

server.address=0.0.0.0
server.port=${PORT:8080}

# ===================================================================
# REPORTES PDF
# ===================================================================

abarrote.reportes.ruta=${user.home}/abarrote-cloud/reportes

# ===================================================================
# ERRORES
# ===================================================================

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=never
server.error.include-exception=false

# ===================================================================
# LOGS DE FLYWAY
# ===================================================================

logging.level.org.flywaydb=INFO
