# ===================================================================
# CONFIGURACIÓN DE BASE DE DATOS POSTGRESQL
# ===================================================================

spring.datasource.url=jdbc:postgresql://localhost:5432/abarrote_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver


# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===================================================================
# CONFIGURACIÓN DEL SERVIDOR
# ===================================================================

server.address=0.0.0.0


# ===================================================================
# REPORTES PDF
# ===================================================================

# Los PDF se organizarán automáticamente por año y mes.
#
# Ejemplo:
#
# /home/tonatiuh/abarrote-cloud/reportes/
# └── 2026/
#     └── 07-julio/
#         └── reporte-ventas-2026-07-01-a-2026-07-13-2026-07-13-120000.pdf

abarrote.reportes.ruta=${user.home}/abarrote-cloud/reportes
