# ===================================================================
# CONFIGURACIÓN DE LA BASE DE DATOS (PostgreSQL)
# ===================================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/abarrote_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# CONFIGURACIÓN DE JPA / HIBERNATE
# ===================================================================
# 'update' creará las tablas automáticamente si no existen, sin borrar tus datos actuales.
spring.jpa.hibernate.ddl-auto=update

# Muestra en la consola de la terminal las consultas SQL reales que hace el sistema (esencial para auditar)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Forzar el dialecto correcto para características avanzadas de PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.address=0.0.0.0
