-- ============================================================
-- ABARROTE CLOUD
-- V1 - ESTRUCTURA INICIAL
--
-- Esta migración se ejecuta en bases nuevas.
--
-- En la base existente de Render, Flyway registrará un baseline
-- en versión 1 y no intentará recrear las tablas existentes.
-- ============================================================

-- ============================================================
-- CATEGORIA
-- ============================================================

CREATE TABLE IF NOT EXISTS categoria (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    nombre VARCHAR(255)
        NOT NULL,

    descripcion VARCHAR(255),

    CONSTRAINT uk_categoria_nombre
        UNIQUE (nombre)
);

-- ============================================================
-- SUCURSAL
-- ============================================================

CREATE TABLE IF NOT EXISTS sucursal (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    activa BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    codigo VARCHAR(20)
        NOT NULL,

    direccion VARCHAR(250),

    fecha_creacion TIMESTAMP(6)
        WITHOUT TIME ZONE
        NOT NULL,

    nombre VARCHAR(120)
        NOT NULL,

    telefono VARCHAR(20),

    CONSTRAINT uk_sucursal_codigo
        UNIQUE (codigo)
);

-- ============================================================
-- PRODUCTO
-- ============================================================

CREATE TABLE IF NOT EXISTS producto (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    activo BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    codigo_barras VARCHAR(50),

    descripcion VARCHAR(255),

    nombre VARCHAR(100)
        NOT NULL,

    precio_compra NUMERIC(10, 2)
        NOT NULL,

    precio_venta NUMERIC(10, 2)
        NOT NULL,

    stock INTEGER
        NOT NULL
        DEFAULT 0,

    stock_minimo INTEGER
        NOT NULL
        DEFAULT 5,

    categoria_id BIGINT,

    CONSTRAINT uk_producto_codigo_barras
        UNIQUE (codigo_barras),

    CONSTRAINT fk_producto_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categoria(id),

    CONSTRAINT ck_producto_stock_no_negativo
        CHECK (stock >= 0),

    CONSTRAINT ck_producto_stock_minimo_no_negativo
        CHECK (stock_minimo >= 0),

    CONSTRAINT ck_producto_precio_compra_no_negativo
        CHECK (precio_compra >= 0),

    CONSTRAINT ck_producto_precio_venta_no_negativo
        CHECK (precio_venta >= 0)
);

-- ============================================================
-- USUARIO
-- ============================================================

CREATE TABLE IF NOT EXISTS usuario (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    activo BOOLEAN
        NOT NULL
        DEFAULT TRUE,

    nombre VARCHAR(120)
        NOT NULL,

    password VARCHAR(255)
        NOT NULL,

    rol VARCHAR(30)
        NOT NULL,

    username VARCHAR(20)
        NOT NULL,

    sucursal_id BIGINT,

    CONSTRAINT uk_usuario_username
        UNIQUE (username),

    CONSTRAINT fk_usuario_sucursal
        FOREIGN KEY (sucursal_id)
        REFERENCES sucursal(id)
);

-- ============================================================
-- INVENTARIO POR SUCURSAL
-- ============================================================

CREATE TABLE IF NOT EXISTS inventario_sucursal (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    existencia INTEGER
        NOT NULL
        DEFAULT 0,

    fecha_actualizacion TIMESTAMP(6)
        WITHOUT TIME ZONE
        NOT NULL,

    stock_minimo INTEGER
        NOT NULL
        DEFAULT 5,

    version BIGINT,

    producto_id BIGINT
        NOT NULL,

    sucursal_id BIGINT
        NOT NULL,

    CONSTRAINT uk_inventario_sucursal_producto
        UNIQUE (
            sucursal_id,
            producto_id
        ),

    CONSTRAINT fk_inventario_producto
        FOREIGN KEY (producto_id)
        REFERENCES producto(id),

    CONSTRAINT fk_inventario_sucursal
        FOREIGN KEY (sucursal_id)
        REFERENCES sucursal(id),

    CONSTRAINT ck_inventario_existencia_no_negativa
        CHECK (existencia >= 0),

    CONSTRAINT ck_inventario_stock_minimo_no_negativo
        CHECK (stock_minimo >= 0)
);

CREATE INDEX IF NOT EXISTS idx_inventario_producto
    ON inventario_sucursal(producto_id);

CREATE INDEX IF NOT EXISTS idx_inventario_sucursal
    ON inventario_sucursal(sucursal_id);

-- ============================================================
-- VENTA
-- ============================================================

CREATE TABLE IF NOT EXISTS venta (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    estado VARCHAR(20)
        NOT NULL,

    fecha_hora TIMESTAMP(6)
        WITHOUT TIME ZONE
        NOT NULL,

    total NUMERIC(12, 2)
        NOT NULL,

    sucursal_id BIGINT,

    usuario_id BIGINT
        NOT NULL,

    CONSTRAINT fk_venta_sucursal
        FOREIGN KEY (sucursal_id)
        REFERENCES sucursal(id),

    CONSTRAINT fk_venta_usuario
        FOREIGN KEY (usuario_id)
        REFERENCES usuario(id),

    CONSTRAINT venta_estado_check
        CHECK (
            estado IN (
                'COMPLETADA',
                'CANCELADA'
            )
        ),

    CONSTRAINT ck_venta_total_no_negativo
        CHECK (total >= 0)
);

CREATE INDEX IF NOT EXISTS idx_venta_fecha_hora
    ON venta(fecha_hora);

CREATE INDEX IF NOT EXISTS idx_venta_sucursal
    ON venta(sucursal_id);

CREATE INDEX IF NOT EXISTS idx_venta_usuario
    ON venta(usuario_id);

-- ============================================================
-- DETALLE DE VENTA
-- ============================================================

CREATE TABLE IF NOT EXISTS detalle_venta (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    cantidad INTEGER,

    precio_unitario NUMERIC(38, 2),

    subtotal NUMERIC(38, 2),

    producto_id BIGINT
        NOT NULL,

    venta_id BIGINT
        NOT NULL,

    CONSTRAINT fk_detalle_venta_venta
        FOREIGN KEY (venta_id)
        REFERENCES venta(id),

    CONSTRAINT fk_detalle_venta_producto
        FOREIGN KEY (producto_id)
        REFERENCES producto(id),

    CONSTRAINT ck_detalle_cantidad_positiva
        CHECK (
            cantidad IS NULL
            OR cantidad > 0
        ),

    CONSTRAINT ck_detalle_precio_no_negativo
        CHECK (
            precio_unitario IS NULL
            OR precio_unitario >= 0
        ),

    CONSTRAINT ck_detalle_subtotal_no_negativo
        CHECK (
            subtotal IS NULL
            OR subtotal >= 0
        )
);

CREATE INDEX IF NOT EXISTS idx_detalle_venta
    ON detalle_venta(venta_id);

CREATE INDEX IF NOT EXISTS idx_detalle_producto
    ON detalle_venta(producto_id);

-- ============================================================
-- MOVIMIENTO DE INVENTARIO
-- ============================================================

CREATE TABLE IF NOT EXISTS movimiento_inventario (

    id BIGINT
        GENERATED BY DEFAULT AS IDENTITY
        PRIMARY KEY,

    folio VARCHAR(36)
        NOT NULL,

    producto_id BIGINT
        NOT NULL,

    sucursal_origen_id BIGINT
        NOT NULL,

    sucursal_destino_id BIGINT
        NOT NULL,

    cantidad INTEGER
        NOT NULL,

    existencia_origen_anterior INTEGER
        NOT NULL,

    existencia_origen_nueva INTEGER
        NOT NULL,

    existencia_destino_anterior INTEGER
        NOT NULL,

    existencia_destino_nueva INTEGER
        NOT NULL,

    usuario_responsable VARCHAR(100)
        NOT NULL,

    motivo VARCHAR(500),

    estado VARCHAR(20)
        NOT NULL,

    fecha_movimiento TIMESTAMP(6)
        WITHOUT TIME ZONE
        NOT NULL,

    CONSTRAINT uk_movimiento_folio
        UNIQUE (folio),

    CONSTRAINT fk_movimiento_producto
        FOREIGN KEY (producto_id)
        REFERENCES producto(id),

    CONSTRAINT fk_movimiento_origen
        FOREIGN KEY (sucursal_origen_id)
        REFERENCES sucursal(id),

    CONSTRAINT fk_movimiento_destino
        FOREIGN KEY (sucursal_destino_id)
        REFERENCES sucursal(id),

    CONSTRAINT ck_movimiento_cantidad_positiva
        CHECK (cantidad > 0),

    CONSTRAINT ck_movimiento_sucursales_distintas
        CHECK (
            sucursal_origen_id
            <> sucursal_destino_id
        ),

    CONSTRAINT ck_movimiento_estado
        CHECK (
            estado IN (
                'APLICADO',
                'CANCELADO'
            )
        ),

    CONSTRAINT ck_movimiento_origen_anterior
        CHECK (
            existencia_origen_anterior >= 0
        ),

    CONSTRAINT ck_movimiento_origen_nueva
        CHECK (
            existencia_origen_nueva >= 0
        ),

    CONSTRAINT ck_movimiento_destino_anterior
        CHECK (
            existencia_destino_anterior >= 0
        ),

    CONSTRAINT ck_movimiento_destino_nueva
        CHECK (
            existencia_destino_nueva >= 0
        )
);

CREATE INDEX IF NOT EXISTS idx_movimiento_fecha
    ON movimiento_inventario(fecha_movimiento);

CREATE INDEX IF NOT EXISTS idx_movimiento_producto
    ON movimiento_inventario(producto_id);

CREATE INDEX IF NOT EXISTS idx_movimiento_origen
    ON movimiento_inventario(sucursal_origen_id);

CREATE INDEX IF NOT EXISTS idx_movimiento_destino
    ON movimiento_inventario(sucursal_destino_id);
